services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - GOFLAGS=-mod=mod
    command: ["go", "build", "-trimpath", "./..."]
